version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: cd flow-graphql
      - run: ls
      - run: yarn install
      - run: ls
      - run: yarn flow 
